# Generated by Django 5.0.6 on 2024-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_categories_alter_women_options_women_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='category',
        ),
        migrations.AddField(
            model_name='women',
            name='categories',
            field=models.ManyToManyField(related_name='women', to='women.categories'),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
