# Generated by Django 5.0.6 on 2024-07-02 14:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('women', '0003_remove_women_category_women_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='categories',
            new_name='cat',
        ),
        migrations.AddField(
            model_name='women',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
