# Generated by Django 5.0.7 on 2024-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_women_cat_alter_women_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/'),
        ),
    ]
